### PR TITLE
Fix source remove

### PR DESCRIPTION
**Pull request by kobynet**
Added fix where RemoveSource in SelectBuilder was removing the wrong source.

### CODE REVIEW

**Comment by jehugaleahsa** [comment]
Thanks for this pull request. Nothing makes me happier than seeing unit tests. Sorry I am not responding any quicker. My job has been really taking it out of me lately. That, and I have two little kids -- so I don't get as much time as I used to. Hoping to circle back on this sooner than later.

**Comment by kobynet** [comment]
I'm more than happy to contribute, you did very nice job with this repo, thanks :)

**Comment by kobynet** [comment]
@jehugaleahsa any chance to merge this anytime soon? or should i use the fork? i prefer to stick to the original repo.

**Comment by jehugaleahsa** [comment]
Your fix should be in the master branch now. Thanks again for your help!

**Comment by kobynet** [comment]
Last thing, any chance for new nuget package? :)

**Comment by jehugaleahsa** [comment]
Already out there.

**Pull request merged**
